/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.app_marcas;

import Extras.Conversion;
import Extras.Sonido;
import Validaciones.Validaciones;
import javax.swing.*;
import Querries.*;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author sotic
 */
public class Interfaz extends javax.swing.JPanel {

    /**
     * Creates new form Interfaz
     */
    public Interfaz() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jButton_entrada = new javax.swing.JButton();
        jButton_salida = new javax.swing.JButton();
        jLabel_titulo = new javax.swing.JLabel();
        jTextField_codigo = new javax.swing.JTextField();
        jTextField_fecha = new javax.swing.JTextField();
        jTextField_hora = new javax.swing.JTextField();
        jLabel_inst_codigo = new javax.swing.JLabel();
        jLabel_inst_fecha = new javax.swing.JLabel();
        jLabel_inst_hora = new javax.swing.JLabel();
        jLabel_subtitulo = new javax.swing.JLabel();
        jComboBox_plantaBD = new javax.swing.JComboBox<>();
        jLabel_plantaBD = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jMenu2.setText("File");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        setForeground(new java.awt.Color(255, 102, 102));

        jButton_entrada.setText("Entrada");
        jButton_entrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_entradaActionPerformed(evt);
            }
        });

        jButton_salida.setText("Salida");
        jButton_salida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_salidaActionPerformed(evt);
            }
        });

        jLabel_titulo.setFont(new java.awt.Font("Segoe UI Black", 0, 24)); // NOI18N
        jLabel_titulo.setText("Marcas");

        jTextField_codigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_codigoActionPerformed(evt);
            }
        });

        jTextField_fecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_fechaActionPerformed(evt);
            }
        });

        jTextField_hora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_horaActionPerformed(evt);
            }
        });

        jLabel_inst_codigo.setText("Código");

        jLabel_inst_fecha.setText("Fecha");

        jLabel_inst_hora.setText("Hora");

        jLabel_subtitulo.setText("Digite los datos en el campo correspondiente");

        jComboBox_plantaBD.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Central", "Guayabo", "Romana" }));

        jLabel_plantaBD.setText("Planta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 120, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBox_plantaBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(20, 20, 20)
                                        .addComponent(jLabel_plantaBD)))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(46, 46, 46)
                                        .addComponent(jTextField_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(91, 91, 91)
                                        .addComponent(jLabel_inst_codigo))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(jButton_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_subtitulo)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(75, 75, 75)
                                        .addComponent(jLabel_titulo)))
                                .addGap(56, 56, 56))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel_inst_fecha))
                            .addComponent(jTextField_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_hora, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addComponent(jLabel_inst_hora)))))
                .addGap(99, 99, 99))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel_subtitulo)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_inst_codigo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel_plantaBD)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox_plantaBD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_inst_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_inst_hora))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_hora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(115, 115, 115))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_salida, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton_entrada, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(41, 41, 41))))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    public void mostrarMensajeEntrada(int codigoError, String idEmpleado, String fecha, String hora) {
        switch (codigoError) {
            case 0 -> {
                Sonido.ReproducirSonido("/sound/GTA-V-Wasted.wav");
                JOptionPane.showMessageDialog(this, 
                        "No existe un empleado con ID " + idEmpleado, "Error", JOptionPane.ERROR_MESSAGE);
            }
            case 1 -> {
                Sonido.ReproducirSonido("/sound/GTA-V-Wasted.wav");
                JOptionPane.showMessageDialog(this, 
                        "El empleado ID " + idEmpleado + " no está activo en la planta", 
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
            case 2 -> {
                Sonido.ReproducirSonido("/sound/GTA-V-Wasted.wav");
                JOptionPane.showMessageDialog(this, 
                        "No puede marcar la entrada. No debe trabajar los " + 
                         Conversion.obtenerDiaSemana(fecha), 
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
            case 3 -> {
                Sonido.ReproducirSonido("/sound/GTA-V-Wasted.wav");
                JOptionPane.showMessageDialog(this, 
                        "No puede marcar la entrada. No debe trabajar por feriado no laborable en la fecha " + fecha, 
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
            case 4 -> {
                Sonido.ReproducirSonido("/sound/GTA-V-Wasted.wav");
                JOptionPane.showMessageDialog(this, 
                        "No puede marcar la entrada. Tiene otra en la misma fecha " + fecha, 
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
            case 5 -> {
                Sonido.ReproducirSonido("/sound/Minecraft-XP-Sound.wav");
                JOptionPane.showMessageDialog(this, 
                        "Se realizó el registro de entrada exitosamente del empleado ID " + idEmpleado +
                                " en la fecha " + fecha + " con la hora de entrada " + hora, 
                        "Éxito", JOptionPane.INFORMATION_MESSAGE);
            }
            default -> {
                Sonido.ReproducirSonido("/sound/GTA-V-Wasted.wav");
                JOptionPane.showMessageDialog(null, 
                        "Error desconocido", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    
     public void mostrarMensajeSalida(int codigoError, String idEmpleado, String fecha, String hora) {
        switch (codigoError) {
            case 0 -> {
                Sonido.ReproducirSonido("/sound/GTA-V-Wasted.wav");
                JOptionPane.showMessageDialog(this, 
                        "No existe un empleado con ID " + idEmpleado, "Error", JOptionPane.ERROR_MESSAGE);
            }
            case 1 -> {
                Sonido.ReproducirSonido("/sound/GTA-V-Wasted.wav");
                JOptionPane.showMessageDialog(this, 
                        "El empleado ID " + idEmpleado + " no está activo en la planta", 
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
            case 2 -> {
                Sonido.ReproducirSonido("/sound/GTA-V-Wasted.wav");
                JOptionPane.showMessageDialog(this, 
                        "No puede marcar la salida. El empleado ID " + idEmpleado + "  no registra entrada en la fecha " + fecha, 
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
            case 3 -> {
                Sonido.ReproducirSonido("/sound/GTA-V-Wasted.wav");
                JOptionPane.showMessageDialog(this, 
                        "No puede marcar la salida. El empleado cuenta con otra salida en la misma fecha " + 
                                fecha, "Error", JOptionPane.ERROR_MESSAGE);
            }
            case 4 -> {
                Sonido.ReproducirSonido("/sound/GTA-V-Wasted.wav");
                JOptionPane.showMessageDialog(this, 
                        "No puede marcar la salida. Marca la hora de salida (" + hora + ") antes que la hora de entrada", 
                        "Error", JOptionPane.ERROR_MESSAGE);
            }
            case 5 -> {
                Sonido.ReproducirSonido("/sound/Minecraft-XP-Sound.wav");
                JOptionPane.showMessageDialog(this, 
                        "Se realizó el registro de salida exitosamente del empleado ID " + idEmpleado +
                                " en la fecha " + fecha + " con la hora de salida " + hora, 
                        "Éxito", JOptionPane.INFORMATION_MESSAGE);
            }
            default -> {
                Sonido.ReproducirSonido("/sound/GTA-V-Wasted.wav");
                JOptionPane.showMessageDialog(this, 
                        "Error desconocido", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }
     
     public boolean validacionesInterfaz(String idEmpleado, String fecha, String hora) {
        if (!Validaciones.validarIdEmpleado(idEmpleado)){
            Sonido.ReproducirSonido("/sound/GTA-V-Wasted.wav");
            JOptionPane.showMessageDialog(this, "Ingrese un id existente (debe ser un número entero)", 
                                    "Error id", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (!Validaciones.validarFecha(fecha)){
            Sonido.ReproducirSonido("/sound/GTA-V-Wasted.wav");
            JOptionPane.showMessageDialog(this, "Ingrese una fecha en el formato YYYY-MM-DD", 
                                    "Error fecha", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        if (!Validaciones.validarHora(hora)){
            Sonido.ReproducirSonido("/sound/GTA-V-Wasted.wav");
            JOptionPane.showMessageDialog(this, "Ingrese una hora en el formato hh:mm:ss", 
                                    "Error hora", JOptionPane.ERROR_MESSAGE);
            return false;
        }
        return true;
    }
     
    private void jButton_entradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_entradaActionPerformed
        String idEmpleado = jTextField_codigo.getText();
        String fecha = jTextField_fecha.getText();
        String hora = jTextField_hora.getText();
        String baseDatos = "planta" + jComboBox_plantaBD.getSelectedItem().toString().toLowerCase();
        
        if (validacionesInterfaz(idEmpleado, fecha, hora))
            try {
                int solucion = SP_empleadoMarcarEntrada.Insertar_Entrada(idEmpleado, fecha, hora, baseDatos);
                mostrarMensajeEntrada(solucion, idEmpleado, fecha, hora);
             } catch (ParseException ex) {
                 Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
             }
    }//GEN-LAST:event_jButton_entradaActionPerformed

    private void jButton_salidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_salidaActionPerformed
        String idEmpleado = jTextField_codigo.getText();
        String fecha = jTextField_fecha.getText();
        String hora = jTextField_hora.getText();
        String baseDatos = "planta" + jComboBox_plantaBD.getSelectedItem().toString().toLowerCase();
        
        if (validacionesInterfaz(idEmpleado, fecha, hora))
            try {
                int solucion = SP_empleadoMarcarSalida.Insertar_Salida(idEmpleado, fecha, hora, baseDatos);
                mostrarMensajeSalida(solucion, idEmpleado, fecha, hora);
             } catch (ParseException ex) {
                 Logger.getLogger(Interfaz.class.getName()).log(Level.SEVERE, null, ex);
             }
    }//GEN-LAST:event_jButton_salidaActionPerformed

    private void jTextField_codigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_codigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_codigoActionPerformed

    private void jTextField_fechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_fechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_fechaActionPerformed

    private void jTextField_horaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_horaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_horaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_entrada;
    private javax.swing.JButton jButton_salida;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JComboBox<String> jComboBox_plantaBD;
    private javax.swing.JLabel jLabel_inst_codigo;
    private javax.swing.JLabel jLabel_inst_fecha;
    private javax.swing.JLabel jLabel_inst_hora;
    private javax.swing.JLabel jLabel_plantaBD;
    private javax.swing.JLabel jLabel_subtitulo;
    private javax.swing.JLabel jLabel_titulo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JTextField jTextField_codigo;
    private javax.swing.JTextField jTextField_fecha;
    private javax.swing.JTextField jTextField_hora;
    // End of variables declaration//GEN-END:variables
}
