/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto2bases_sistemademarcascorp_fabianianjoselynjeison;

import javax.swing.ButtonGroup;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author vmrjo
 */
public class vistaPlanta extends javax.swing.JFrame {

    /**
     * Creates new form VistaPlanta
     */
    public vistaPlanta() {
        initComponents();
        grupoBotones ();
        opcionNull();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        tBtnEmpleados = new javax.swing.JToggleButton();
        tBtnAsistencia = new javax.swing.JToggleButton();
        tBtnCalendario = new javax.swing.JToggleButton();
        tBtnPlanillas = new javax.swing.JToggleButton();
        tBtnConfiguracion = new javax.swing.JToggleButton();
        pnlEncabezado = new javax.swing.JPanel();
        lblNombrePlanta = new javax.swing.JLabel();
        checkModoPrueba = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVista = new javax.swing.JTable();
        lblTitulo = new javax.swing.JLabel();
        lblFiltros = new javax.swing.JLabel();
        comboBoxSupervisores = new javax.swing.JComboBox<>();
        lblSupervisor = new javax.swing.JLabel();
        lblDadosDeBaja = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlFondo.setBackground(javax.swing.UIManager.getDefaults().getColor("Desktop.background"));

        pnlMenu.setBackground(new java.awt.Color(0, 51, 102));

        tBtnEmpleados.setBackground(new java.awt.Color(0, 51, 102));
        tBtnEmpleados.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        tBtnEmpleados.setForeground(new java.awt.Color(255, 255, 255));
        tBtnEmpleados.setText("Empleados");
        tBtnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBtnEmpleadosActionPerformed(evt);
            }
        });

        tBtnAsistencia.setBackground(new java.awt.Color(0, 51, 102));
        tBtnAsistencia.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        tBtnAsistencia.setForeground(new java.awt.Color(255, 255, 255));
        tBtnAsistencia.setText("Asistencia");

        tBtnCalendario.setBackground(new java.awt.Color(0, 51, 102));
        tBtnCalendario.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        tBtnCalendario.setForeground(new java.awt.Color(255, 255, 255));
        tBtnCalendario.setText("Calendario Laboral");
        tBtnCalendario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBtnCalendarioActionPerformed(evt);
            }
        });

        tBtnPlanillas.setBackground(new java.awt.Color(0, 51, 102));
        tBtnPlanillas.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        tBtnPlanillas.setForeground(new java.awt.Color(255, 255, 255));
        tBtnPlanillas.setText("Planillas");

        tBtnConfiguracion.setBackground(new java.awt.Color(0, 51, 102));
        tBtnConfiguracion.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        tBtnConfiguracion.setForeground(new java.awt.Color(255, 255, 255));
        tBtnConfiguracion.setText("Configuración");

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tBtnEmpleados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tBtnAsistencia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tBtnCalendario, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                    .addComponent(tBtnPlanillas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tBtnConfiguracion, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(tBtnEmpleados, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tBtnCalendario, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tBtnAsistencia, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tBtnPlanillas, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 335, Short.MAX_VALUE)
                .addComponent(tBtnConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pnlEncabezado.setBackground(new java.awt.Color(0, 0, 0));

        lblNombrePlanta.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblNombrePlanta.setForeground(new java.awt.Color(255, 255, 255));
        lblNombrePlanta.setText("Nombre de Planta");

        checkModoPrueba.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        checkModoPrueba.setForeground(new java.awt.Color(255, 255, 255));
        checkModoPrueba.setText("Modo Prueba");

        javax.swing.GroupLayout pnlEncabezadoLayout = new javax.swing.GroupLayout(pnlEncabezado);
        pnlEncabezado.setLayout(pnlEncabezadoLayout);
        pnlEncabezadoLayout.setHorizontalGroup(
            pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEncabezadoLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(lblNombrePlanta, javax.swing.GroupLayout.PREFERRED_SIZE, 1035, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(checkModoPrueba, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        pnlEncabezadoLayout.setVerticalGroup(
            pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlEncabezadoLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(pnlEncabezadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombrePlanta, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(checkModoPrueba))
                .addGap(24, 24, 24))
        );

        checkModoPrueba.getAccessibleContext().setAccessibleName("Modo Prueba");
        checkModoPrueba.getAccessibleContext().setAccessibleDescription("");

        tblVista.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblVista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblVista.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(tblVista);
        tblVista.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblTitulo.setForeground(new java.awt.Color(51, 51, 51));
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("Lista de Empleados");

        lblFiltros.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        lblFiltros.setText("Filtros");

        comboBoxSupervisores.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N

        lblSupervisor.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblSupervisor.setText("Supervisor:");

        lblDadosDeBaja.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblDadosDeBaja.setText("Dados de baja:");

        javax.swing.GroupLayout pnlFondoLayout = new javax.swing.GroupLayout(pnlFondo);
        pnlFondo.setLayout(pnlFondoLayout);
        pnlFondoLayout.setHorizontalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFondoLayout.createSequentialGroup()
                .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
                        .addComponent(lblFiltros)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addComponent(lblSupervisor)
                        .addGap(18, 18, 18)
                        .addComponent(comboBoxSupervisores, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblDadosDeBaja))
                .addGap(34, 34, 34))
            .addComponent(pnlEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlFondoLayout.setVerticalGroup(
            pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFondoLayout.createSequentialGroup()
                .addComponent(pnlEncabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblFiltros)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSupervisor)
                            .addComponent(comboBoxSupervisores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblDadosDeBaja))
                    .addGroup(pnlFondoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tBtnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBtnEmpleadosActionPerformed
        if (tBtnEmpleados.isSelected()){
            opcionEmpleados();
        }        
    }//GEN-LAST:event_tBtnEmpleadosActionPerformed

    private void tBtnCalendarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBtnCalendarioActionPerformed
        if (tBtnCalendario.isSelected()){
            opcionCalendario();
        }
    }//GEN-LAST:event_tBtnCalendarioActionPerformed

    private void grupoBotones (){
        ButtonGroup grupoBotones = new ButtonGroup ();
        grupoBotones.add(tBtnEmpleados);
        grupoBotones.add(tBtnCalendario);
        grupoBotones.add(tBtnAsistencia);
        grupoBotones.add(tBtnPlanillas);
        grupoBotones.add(tBtnConfiguracion);
    }
    
    private void opcionNull (){
        lblTitulo.setText("");
        lblFiltros.setVisible(false);
        lblSupervisor.setVisible(false);
        lblDadosDeBaja.setVisible(false);
        comboBoxSupervisores.setVisible(false); 
    }
  
    private void opcionEmpleados (){    
        opcionNull();
        lblTitulo.setText("Lista de Empleados");
        DefaultTableModel modeloTabla = new DefaultTableModel ();
        modeloTabla.addColumn("Código");
        modeloTabla.addColumn("Nombre");
        modeloTabla.addColumn("Apellidos");
        modeloTabla.addColumn("Fecha Ingreso");
        modeloTabla.addColumn("Fecha Salida");
        modeloTabla.addColumn("Salario Bruto");
        modeloTabla.addColumn("Salario / hora");
        modeloTabla.addColumn("Tipo de Empleado");
        modeloTabla.addColumn("Departamento");
        modeloTabla.addColumn("Supervisor");
        tblVista.setModel(modeloTabla);
        if (tblVista.getColumnModel().getColumnCount() > 0) {
            tblVista.getColumnModel().getColumn(0).setResizable(false);
            tblVista.getColumnModel().getColumn(0).setPreferredWidth(36);
            tblVista.getColumnModel().getColumn(1).setResizable(false);
            tblVista.getColumnModel().getColumn(1).setPreferredWidth(73);
            tblVista.getColumnModel().getColumn(2).setResizable(false);
            tblVista.getColumnModel().getColumn(2).setPreferredWidth(125);
            tblVista.getColumnModel().getColumn(3).setResizable(false);
            tblVista.getColumnModel().getColumn(3).setPreferredWidth(75);
            tblVista.getColumnModel().getColumn(4).setResizable(false);
            tblVista.getColumnModel().getColumn(4).setPreferredWidth(70);
            tblVista.getColumnModel().getColumn(5).setResizable(false);
            tblVista.getColumnModel().getColumn(5).setPreferredWidth(75);
            tblVista.getColumnModel().getColumn(6).setResizable(false);
            tblVista.getColumnModel().getColumn(6).setPreferredWidth(82);
            tblVista.getColumnModel().getColumn(7).setResizable(false);
            tblVista.getColumnModel().getColumn(7).setPreferredWidth(100);
            tblVista.getColumnModel().getColumn(8).setResizable(false);
            tblVista.getColumnModel().getColumn(8).setPreferredWidth(80);
            tblVista.getColumnModel().getColumn(9).setResizable(false);
            tblVista.getColumnModel().getColumn(9).setPreferredWidth(55);
        }
        
        //tblEmpleados.setVisible(true);  // luego se le cargan los datos
                
        lblFiltros.setVisible(true);
        lblSupervisor.setVisible(true);
        lblDadosDeBaja.setVisible(true);
        comboBoxSupervisores.setVisible(true);  // luego se cargan la lista de supervisores   
    }

    private void opcionCalendario (){
        opcionNull();
        lblTitulo.setText("Lista de dias no laborables / feriados");
        DefaultTableModel modeloTabla = new DefaultTableModel ();
        modeloTabla.addColumn("ID");
        modeloTabla.addColumn("Dia");
        modeloTabla.addColumn("Tipo de dia");
        modeloTabla.addColumn("Paga");
        tblVista.setModel(modeloTabla);
        
        // poner opcion para agregar otro dia ?
    }
    
    private void opcionAsistencia (){
    
    }
    
    private void opcionPlanillas (){
    
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vistaPlanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vistaPlanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vistaPlanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vistaPlanta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new vistaPlanta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox checkModoPrueba;
    private javax.swing.JComboBox<String> comboBoxSupervisores;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDadosDeBaja;
    private javax.swing.JLabel lblFiltros;
    private javax.swing.JLabel lblNombrePlanta;
    private javax.swing.JLabel lblSupervisor;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlEncabezado;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JToggleButton tBtnAsistencia;
    private javax.swing.JToggleButton tBtnCalendario;
    private javax.swing.JToggleButton tBtnConfiguracion;
    private javax.swing.JToggleButton tBtnEmpleados;
    private javax.swing.JToggleButton tBtnPlanillas;
    private javax.swing.JTable tblVista;
    // End of variables declaration//GEN-END:variables
}
